# Generated by Django 6.0.7 on 2026-07-12 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LootTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('ticket_cost', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LootReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('coins', 'Coins'), ('diamonds', 'Diamonds'), ('cosmetic', 'Cosmetic item')], max_length=10)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('cosmetic_code', models.CharField(blank=True, max_length=40)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='engagement.loottable')),
            ],
        ),
    ]
