# Generated by Django 6.0.6 on 2026-06-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="design_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
