# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('diamonds_per_unit_cash', models.PositiveIntegerField(default=100)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('min_diamonds', models.PositiveIntegerField(default=10000)),
                ('max_diamonds_per_day', models.PositiveIntegerField(default=500000)),
                ('platform_fee_bps', models.PositiveIntegerField(default=2000)),
            ],
        ),
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='unverified', max_length=12)),
                ('legal_name', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('document_type', models.CharField(blank=True, max_length=20)),
                ('document_ref', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bank', 'Bank transfer'), ('paypal', 'PayPal'), ('upi', 'UPI')], max_length=10)),
                ('display', models.CharField(max_length=60)),
                ('processor_token', models.CharField(blank=True, max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('gross_cash_cents', models.PositiveBigIntegerField()),
                ('fee_cents', models.PositiveBigIntegerField()),
                ('net_cash_cents', models.PositiveBigIntegerField()),
                ('currency_code', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('review', 'Under review (fraud/AML)'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='requested', max_length=12)),
                ('risk_score', models.FloatField(default=0.0)),
                ('hold_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor_ref', models.CharField(blank=True, max_length=120)),
                ('debit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_debits', to='economy.transaction')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='payouts.payoutmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayoutAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=12)),
                ('to_status', models.CharField(max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='payouts.payoutrequest')),
            ],
        ),
        migrations.AddIndex(
            model_name='payoutrequest',
            index=models.Index(fields=['status', '-created_at'], name='payouts_pay_status_4f3e8f_idx'),
        ),
    ]
