# Generated by Django 4.2.7 on 2025-09-23 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Font Awesome icon class", max_length=50
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Service Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("width_mm", models.FloatField(help_text="Width in millimeters")),
                ("height_mm", models.FloatField(help_text="Height in millimeters")),
                (
                    "bleed_mm",
                    models.FloatField(
                        default=3.0, help_text="Bleed size in millimeters"
                    ),
                ),
                (
                    "safe_zone_mm",
                    models.FloatField(
                        default=5.0, help_text="Safe zone in millimeters"
                    ),
                ),
                ("dpi", models.IntegerField(default=300, help_text="Print resolution")),
                (
                    "has_design_tool",
                    models.BooleanField(
                        default=False, help_text="Enable design tool for this product"
                    ),
                ),
                (
                    "allows_upload",
                    models.BooleanField(default=True, help_text="Allow file uploads"),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("minimum_quantity", models.IntegerField(default=1)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="services.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
