# Generated by Django 4.2.7 on 2025-09-26 19:18

from django.db import migrations, models
import django.db.models.deletion
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(max_length=300)),
                ('design_tool_enabled', models.BooleanField(default=False, help_text='Enable design tool for this product')),
                ('canvas_width', models.IntegerField(blank=True, null=True, help_text='Canvas width in pixels for design tool')),
                ('canvas_height', models.IntegerField(blank=True, null=True, help_text='Canvas height in pixels for design tool')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='products/featured/', help_text='Main product image')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='products/hero/', help_text='Hero section image')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[MinValueValidator(Decimal('0.01'))])),
                ('price_unit', models.CharField(default='per piece', help_text='e.g., per piece, per page, per 100 pieces', max_length=50)),
                ('available_sizes', models.JSONField(default=list, help_text='List of available sizes with price modifiers. Format: [{\'name\': \'A4\', \'price_modifier\': 0}, ...]')),
                ('available_papers', models.JSONField(default=list, help_text='List of paper types with price modifiers. Format: [{\'name\': \'80 GSM\', \'price_modifier\': 25}, ...]')),
                ('available_finishes', models.JSONField(default=list, help_text='List of finishes with price modifiers. Format: [{\'name\': \'Matte\', \'price_modifier\': 50}, ...]')),
                ('available_bindings', models.JSONField(default=list, help_text='List of binding options with price modifiers. Format: [{\'name\': \'Saddle Stitch\', \'price_modifier\': 0}, ...]')),
                ('color_options', models.JSONField(default=list, help_text='List of color options with price modifiers. Format: [{\'name\': \'Full Color\', \'price_modifier\': 200}, ...]')),
                ('quantity_tiers', models.JSONField(default=list, help_text='Quantity-based pricing tiers. Format: [{\'min_qty\': 100, \'max_qty\': 249, \'discount_percent\': 0}, ...]')),
                ('rush_order_available', models.BooleanField(default=True)),
                ('rush_order_percentage', models.IntegerField(default=50, help_text='Rush order surcharge percentage')),
                ('design_service_available', models.BooleanField(default=True)),
                ('design_service_price', models.DecimalField(decimal_places=2, default=Decimal('999.00'), max_digits=8)),
                ('key_features', models.JSONField(default=list, help_text='List of key features. Format: [{\'title\': \'High Quality\', \'description\': \'Premium materials\'}, ...]')),
                ('specifications', models.JSONField(default=dict, help_text='Product specifications. Format: {\'Material\': \'300 GSM Art Paper\', \'Size\': \'Custom sizes available\'}')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_products', to='services.servicecategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
