# Generated by Django 5.2.6 on 2025-09-27 04:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20250927_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Economy, Standard, Premium', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated delivery days')),
                ('is_express', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AddField(
            model_name='product',
            name='allows_custom_size',
            field=models.BooleanField(default=False, help_text='Allow custom sizing'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_discount_text',
            field=models.CharField(blank=True, help_text='Text describing bulk discount offer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet_file',
            field=models.FileField(blank=True, help_text='Optional product datasheet PDF', null=True, upload_to='product_datasheets/'),
        ),
        migrations.AddField(
            model_name='product',
            name='express_production',
            field=models.BooleanField(default=False, help_text='Whether express production is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section main image', null=True, upload_to='products/hero/'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_quote',
            field=models.CharField(blank=True, help_text='Hero section quote or tagline', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Hero section subtitle/description', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Hero section main title', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='product_og_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_color_image',
            field=models.ImageField(blank=True, help_text='Sample image for color selection grid', null=True, upload_to='products/sample_color/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_file',
            field=models.FileField(blank=True, help_text='Optional downloadable sample file', null=True, upload_to='product_samples/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_paper_image',
            field=models.ImageField(blank=True, help_text='Sample image for paper selection grid', null=True, upload_to='products/sample_paper/'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief product description', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='trust_badges',
            field=models.CharField(blank=True, help_text='Comma-separated trust badge names or image URLs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional product video URL', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base setup cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='bleed_mm',
            field=models.FloatField(default=3.0, help_text='Bleed size in millimeters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='dpi',
            field=models.IntegerField(default=300, help_text='Print resolution', validators=[django.core.validators.MinValueValidator(72)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_mm',
            field=models.FloatField(help_text='Height in millimeters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='safe_zone_mm',
            field=models.FloatField(default=5.0, help_text='Safe zone in millimeters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_mm',
            field=models.FloatField(help_text='Width in millimeters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class or image URL', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_processes/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='services.product')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='product_samples/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_sample_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Material, Dimensions', max_length=100)),
                ('value', models.CharField(help_text='e.g., 300gsm Art Paper, 105x148mm', max_length=200)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show prominently')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='services.product')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='StaticProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.staticproduct')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.staticproduct')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticProductSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='products/samples/')),
                ('file', models.FileField(blank=True, null=True, upload_to='products/sample_files/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='services.staticproduct')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StaticProductTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_company', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='services.staticproduct')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'color', 'paper_type')", max_length=100)),
                ('field_label', models.CharField(help_text="Display label (e.g., 'Color', 'Paper Type')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('select', 'Select Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('range', 'Range Slider')], default='select', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('options', models.TextField(blank=True, help_text='JSON format: [{"value": "option1", "label": "Option 1", "price_modifier": 0}]')),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('show_condition', models.CharField(blank=True, help_text='JSON condition for when to show this field', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='services.product')),
            ],
            options={
                'ordering': ['order', 'field_name'],
                'unique_together': {('product', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, help_text='e.g., A4, A5, Custom', max_length=100)),
                ('page_count', models.PositiveIntegerField(default=1, help_text='Number of pages')),
                ('paper_type', models.CharField(blank=True, help_text='e.g., 70gsm, 80gsm, Art Paper', max_length=100)),
                ('binding_type', models.CharField(blank=True, help_text='e.g., Perfect, Spiral, Saddle Stitched, Hard Cover, Soft Cover', max_length=100)),
                ('finish', models.CharField(blank=True, help_text='e.g., Matte, Glossy, Velvet', max_length=100)),
                ('colors', models.CharField(blank=True, help_text='e.g., Black & White, Full Color, 4+4, 4+0', max_length=20)),
                ('print_sides', models.CharField(blank=True, help_text='Single-sided, Double-sided', max_length=20)),
                ('cover_finish', models.CharField(blank=True, help_text='e.g., Matte, Glossy, Velvet', max_length=50)),
                ('design_service', models.BooleanField(default=False, help_text='Include design/formatting service')),
                ('isbn_allocation', models.BooleanField(default=False, help_text='ISBN allocation included')),
                ('optional_finishing', models.CharField(blank=True, help_text='e.g., Lamination, UV, Foiling', max_length=100)),
                ('min_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('setup_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='One-time setup cost', max_digits=10)),
                ('volume_discount_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount for this tier', max_digits=5)),
                ('rush_order_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Rush order price multiplier', max_digits=4)),
                ('delivery_speed', models.CharField(blank=True, help_text='e.g., Standard, Express', max_length=50)),
                ('delivery_location', models.CharField(blank=True, help_text='For location-based pricing', max_length=100)),
                ('turnaround_days', models.PositiveIntegerField(default=5, help_text='Standard turnaround time in days')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this pricing tier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='services.product')),
            ],
            options={
                'verbose_name': 'Product Pricing',
                'verbose_name_plural': 'Product Pricings',
                'ordering': ['product', 'min_quantity'],
                'unique_together': {('product', 'size', 'paper_type', 'binding_type', 'finish', 'colors', 'min_quantity')},
            },
        ),
    ]
