# Generated by Django 5.2.6 on 2025-09-24 10:31

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_productpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Economy, Standard, Premium', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6B7280', help_text='Hex color code', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productpricing',
            options={'ordering': ['product', 'min_quantity'], 'verbose_name': 'Product Pricing', 'verbose_name_plural': 'Product Pricings'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='productpricing',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='allows_custom_size',
            field=models.BooleanField(default=False, help_text='Allow custom sizing'),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief product description', max_length=300),
        ),
        migrations.AddField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='colors',
            field=models.CharField(blank=True, help_text='e.g., 4+4, 4+0', max_length=20),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this pricing tier'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or conditions'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='rush_order_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Rush order price multiplier', max_digits=4),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='setup_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='One-time setup cost', max_digits=10),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='turnaround_days',
            field=models.PositiveIntegerField(default=5, help_text='Standard turnaround time in days'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='volume_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage discount for this tier', max_digits=5),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Show prominently'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base setup cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='bleed_mm',
            field=models.FloatField(default=3.0, help_text='Bleed size in millimeters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='dpi',
            field=models.IntegerField(default=300, help_text='Print resolution', validators=[django.core.validators.MinValueValidator(72)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_mm',
            field=models.FloatField(help_text='Height in millimeters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default price per unit', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='safe_zone_mm',
            field=models.FloatField(default=5.0, help_text='Safe zone in millimeters', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_mm',
            field=models.FloatField(help_text='Width in millimeters', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='binding_type',
            field=models.CharField(blank=True, help_text='e.g., Saddle Stitched', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='finish',
            field=models.CharField(blank=True, help_text='e.g., Matte Lamination', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='paper_type',
            field=models.CharField(blank=True, help_text='e.g., 300gsm Art Paper', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='size',
            field=models.CharField(blank=True, help_text='e.g., A4, A5, Custom', max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='e.g., Material, Dimensions', max_length=100),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='value',
            field=models.CharField(help_text='e.g., 300gsm Art Paper, 105x148mm', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='productpricing',
            unique_together={('product', 'size', 'paper_type', 'binding_type', 'finish', 'colors', 'min_quantity')},
        ),
    ]
