# Generated by Django 4.2.7 on 2025-09-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_pricingtier_shippingoption_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productformfield",
            options={
                "ordering": ["section_order", "field_section", "order", "field_name"]
            },
        ),
        migrations.AlterUniqueTogether(
            name="productformfield",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="calculation_formula",
            field=models.TextField(
                blank=True, help_text="Custom calculation formula for complex pricing"
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="css_classes",
            field=models.CharField(
                blank=True,
                help_text="Additional CSS classes for styling",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="field_section",
            field=models.CharField(
                choices=[
                    ("product_specs", "Product Specifications"),
                    ("design_options", "Design Options"),
                    ("printing_options", "Printing Options"),
                    ("finishing_options", "Finishing Options"),
                    ("additional_services", "Additional Services"),
                    ("file_uploads", "File Uploads"),
                    ("quantity_pricing", "Quantity & Pricing"),
                ],
                default="product_specs",
                help_text="Section to group this field under",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="grid_columns",
            field=models.IntegerField(
                default=1, help_text="Number of columns this field should span (1-3)"
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="is_price_affecting",
            field=models.BooleanField(
                default=True, help_text="Whether this field affects the final price"
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="placeholder",
            field=models.CharField(
                blank=True, help_text="Input placeholder text", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="section_order",
            field=models.IntegerField(
                default=0, help_text="Order of the section itself"
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="static_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="services.staticproduct",
            ),
        ),
        migrations.AddField(
            model_name="productformfield",
            name="triggers_fields",
            field=models.TextField(
                blank=True,
                help_text='JSON array of field names this field can trigger: ["bw_page_count", "color_page_count"]',
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="field_label",
            field=models.CharField(
                help_text="Display label (e.g., 'Interior Color', 'Paper Type')",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="field_name",
            field=models.CharField(
                help_text="Internal field name (e.g., 'interior_color', 'paper_type')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Input"),
                    ("number", "Number Input"),
                    ("select", "Select Dropdown"),
                    ("radio", "Radio Buttons"),
                    ("checkbox", "Checkbox"),
                    ("range", "Range Slider"),
                    ("file", "File Upload"),
                    ("conditional_group", "Conditional Field Group"),
                ],
                default="select",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="help_text",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="options",
            field=models.TextField(
                blank=True,
                help_text='JSON format: [{"value": "option1", "label": "Option 1", "price_modifier": 0, "description": ""}]',
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Display order within section"
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="services.product",
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="show_condition",
            field=models.TextField(
                blank=True,
                help_text='JSON condition: {"field": "interior_color", "value": "combine_color", "operator": "equals"}',
            ),
        ),
    ]
