# Generated by Django 5.2.6 on 2025-09-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_pricingtier_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_days', models.PositiveIntegerField(help_text='Estimated delivery days')),
                ('is_express', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_discount_text',
            field=models.CharField(blank=True, help_text='Text describing bulk discount offer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='datasheet_file',
            field=models.FileField(blank=True, help_text='Optional product datasheet PDF', null=True, upload_to='product_datasheets/'),
        ),
        migrations.AddField(
            model_name='product',
            name='express_production',
            field=models.BooleanField(default=False, help_text='Whether express production is available'),
        ),
        migrations.AddField(
            model_name='product',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Open Graph image for social sharing', null=True, upload_to='product_og_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_file',
            field=models.FileField(blank=True, help_text='Optional downloadable sample file', null=True, upload_to='product_samples/'),
        ),
        migrations.AddField(
            model_name='product',
            name='trust_badges',
            field=models.CharField(blank=True, help_text='Comma-separated trust badge names or image URLs', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional product video URL', null=True),
        ),
        migrations.CreateModel(
            name='ProductFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon class or image URL', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_processes/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='services.product')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='product_samples/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_sample_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='services.product')),
            ],
        ),
    ]
