# Generated by Django 4.2.7 on 2025-09-27 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0004_alter_productformfield_options_and_more"),
    ]

    operations = []
