# Generated by Django 5.2.6 on 2025-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_shippingoption_product_bulk_discount_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='cover_finish',
            field=models.CharField(blank=True, help_text='e.g., Matte, Glossy, Velvet', max_length=50),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='For location-based pricing', max_length=100),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='delivery_speed',
            field=models.CharField(blank=True, help_text='e.g., Standard, Express', max_length=50),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='design_service',
            field=models.BooleanField(default=False, help_text='Include design/formatting service'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='isbn_allocation',
            field=models.BooleanField(default=False, help_text='ISBN allocation included'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='optional_finishing',
            field=models.CharField(blank=True, help_text='e.g., Lamination, UV, Foiling', max_length=100),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='page_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of pages'),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='print_sides',
            field=models.CharField(blank=True, help_text='Single-sided, Double-sided', max_length=20),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='binding_type',
            field=models.CharField(blank=True, help_text='e.g., Perfect, Spiral, Saddle Stitched, Hard Cover, Soft Cover', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='colors',
            field=models.CharField(blank=True, help_text='e.g., Black & White, Full Color, 4+4, 4+0', max_length=20),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='finish',
            field=models.CharField(blank=True, help_text='e.g., Matte, Glossy, Velvet', max_length=100),
        ),
        migrations.AlterField(
            model_name='productpricing',
            name='paper_type',
            field=models.CharField(blank=True, help_text='e.g., 70gsm, 80gsm, Art Paper', max_length=100),
        ),
    ]
