# Generated by Django 4.2.7 on 2025-09-28 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("design_tool", "0002_alter_designsession_product"),
        ("services", "0007_auto_20250928_2009"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="productfeature",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.AlterUniqueTogether(
            name="productpricing",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="productpricing",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productprocess",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productsample",
            name="product",
        ),
        migrations.RemoveField(
            model_name="productspecification",
            name="product",
        ),
        migrations.RemoveField(
            model_name="producttestimonial",
            name="product",
        ),
        migrations.AlterModelOptions(
            name="pricingtier",
            options={"ordering": ["min_quantity"]},
        ),
        migrations.AlterModelOptions(
            name="productformfield",
            options={"ordering": ["static_product", "section_order", "order"]},
        ),
        migrations.AlterModelOptions(
            name="staticproductfaq",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="staticproductimage",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="staticproductsample",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="staticproducttestimonial",
            options={"ordering": ["order"]},
        ),
        migrations.RenameField(
            model_name="staticproducttestimonial",
            old_name="content",
            new_name="testimonial",
        ),
        migrations.RemoveField(
            model_name="shippingoption",
            name="estimated_days",
        ),
        migrations.RemoveField(
            model_name="shippingoption",
            name="is_express",
        ),
        migrations.RemoveField(
            model_name="staticproductsample",
            name="file",
        ),
        migrations.RemoveField(
            model_name="staticproductsample",
            name="image",
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="discount_percentage",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="max_quantity",
            field=models.IntegerField(
                blank=True, help_text="Leave blank for unlimited", null=True
            ),
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="min_quantity",
            field=models.IntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_tiers",
                to="services.staticproduct",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productformfield",
            name="price_modifier",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Base price modifier for this field",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="shippingoption",
            name="delivery_days_max",
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoption",
            name="delivery_days_min",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shippingoption",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staticproduct",
            name="turnaround_time",
            field=models.CharField(
                blank=True, help_text="e.g., '3-5 business days'", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="staticproductsample",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="staticproductsample",
            name="file_size",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="staticproductsample",
            name="file_type",
            field=models.CharField(
                default="PDF",
                help_text="e.g., PDF, AI, PSD",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staticproductsample",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="staticproductsample",
            name="sample_file",
            field=models.FileField(
                default="samples/default.pdf", upload_to="product_samples/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staticproductsample",
            name="thumbnail",
            field=models.ImageField(blank=True, upload_to="product_samples/thumbs/"),
        ),
        migrations.AddField(
            model_name="staticproducttestimonial",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="css_classes",
            field=models.CharField(
                blank=True, help_text="Additional CSS classes", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="grid_columns",
            field=models.IntegerField(default=1, help_text="Grid columns span (1-3)"),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="is_price_affecting",
            field=models.BooleanField(
                default=False, help_text="Does this field affect pricing calculations?"
            ),
        ),
        migrations.AlterField(
            model_name="productformfield",
            name="static_product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="services.staticproduct",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="staticproductfaq",
            name="question",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="staticproductsample",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="staticproducttestimonial",
            name="customer_company",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="staticproducttestimonial",
            name="customer_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="staticproducttestimonial",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricingtier",
            unique_together={("product", "min_quantity")},
        ),
        migrations.DeleteModel(
            name="ProductFAQ",
        ),
        migrations.DeleteModel(
            name="ProductFeature",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="ProductPricing",
        ),
        migrations.DeleteModel(
            name="ProductProcess",
        ),
        migrations.DeleteModel(
            name="ProductSample",
        ),
        migrations.DeleteModel(
            name="ProductSpecification",
        ),
        migrations.DeleteModel(
            name="ProductTestimonial",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="color",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="description",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="name",
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="order",
        ),
        migrations.RemoveField(
            model_name="productformfield",
            name="calculation_formula",
        ),
        migrations.RemoveField(
            model_name="productformfield",
            name="product",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
