# Generated by Django 5.2.6 on 2025-09-28 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20250928_0202'),
    ]

    operations = [
        migrations.RunSQL("""
            DELETE FROM services_productformfield
            WHERE id NOT IN (
                SELECT MIN(id)
                FROM services_productformfield
                GROUP BY product_id, field_name
            );
        """, reverse_sql=migrations.RunSQL.noop),
    ]
