# Generated by Django 5.2.6 on 2025-10-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productformfield',
            unique_together={('static_product', 'field_name')},
        ),
        migrations.CreateModel(
            name='CategoryFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('book-printing', 'Book Printing'), ('paper-boxes', 'Paper Boxes'), ('marketing-material', 'Marketing Material'), ('stationery', 'Stationery')], max_length=50)),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'interior_color', 'paper_type')", max_length=100)),
                ('field_label', models.CharField(help_text="Display label (e.g., 'Interior Color', 'Paper Type')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('select', 'Select Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('range', 'Range Slider'), ('file', 'File Upload'), ('conditional_group', 'Conditional Field Group')], default='select', max_length=20)),
                ('section', models.CharField(choices=[('interior_color', 'Interior Color'), ('book_size_pages', 'Book Size And Page Count'), ('paper_type', 'Paper Type'), ('binding_type', 'Binding Type'), ('cover_finish', 'Cover Finish'), ('designing_formatting', 'Designing And Formatting'), ('isbn_allocation', 'ISBN Allocation'), ('box_dimensions', 'Box Dimensions'), ('material_type', 'Material Type'), ('printing_options', 'Printing Options'), ('finishing_options', 'Finishing Options'), ('material_type_selection', 'Material Type Selection'), ('size_options', 'Size Options'), ('design_options', 'Design Options'), ('stationery_type', 'Stationery Type'), ('specifications', 'Specifications'), ('additional_services', 'Additional Services'), ('file_uploads', 'File Uploads'), ('quantity_pricing', 'Quantity & Pricing')], help_text='Section to group this field under', max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order within section')),
                ('section_order', models.IntegerField(default=0, help_text='Order of the section itself')),
                ('help_text', models.CharField(blank=True, max_length=500)),
                ('placeholder', models.CharField(blank=True, help_text='Input placeholder text', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Section description text')),
                ('options', models.JSONField(blank=True, default=list, help_text='List of field options. Format: [{"value": "option1", "label": "Option 1", "price_modifier": 0, "description": ""}]')),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('show_condition', models.JSONField(blank=True, default=dict, help_text='Condition for showing this field. Format: {"field": "interior_color", "value": "combine_color", "operator": "equals"}')),
                ('triggers_fields', models.JSONField(blank=True, default=list, help_text='Array of field names this field can trigger: ["bw_page_count", "color_page_count"]')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules for the field. Format: {"min_pages_for_binding": 30, "allowed_file_types": ["pdf", "doc", "docx"]}')),
                ('css_classes', models.CharField(blank=True, help_text='Additional CSS classes', max_length=200)),
                ('grid_columns', models.IntegerField(default=1, help_text='Grid columns span (1-3)')),
                ('is_price_affecting', models.BooleanField(default=False, help_text='Does this field affect pricing calculations?')),
                ('price_modifier_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage'), ('per_unit', 'Per Unit'), ('conditional', 'Conditional Logic')], default='fixed', max_length=20)),
                ('price_modifier_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_modifier_conditions', models.JSONField(blank=True, default=dict, help_text='Conditional pricing rules. Format: {"combine_color": {"bw_pages": 2.5, "color_pages": 8.0}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Form Field',
                'verbose_name_plural': 'Category Form Fields',
                'ordering': ['category', 'section_order', 'order'],
                'unique_together': {('category', 'field_name')},
            },
        ),
    ]
