# Generated by Django 5.2.6 on 2025-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_productpricing_cover_finish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section main image', null=True, upload_to='products/hero/'),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_quote',
            field=models.CharField(blank=True, help_text='Hero section quote or tagline', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Hero section subtitle/description', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Hero section main title', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_color_image',
            field=models.ImageField(blank=True, help_text='Sample image for color selection grid', null=True, upload_to='products/sample_color/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sample_paper_image',
            field=models.ImageField(blank=True, help_text='Sample image for paper selection grid', null=True, upload_to='products/sample_paper/'),
        ),
    ]
