# Generated by Django 5.2.6 on 2025-09-26 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_product_hero_image_product_hero_quote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Internal field name (e.g., 'color', 'paper_type')", max_length=100)),
                ('field_label', models.CharField(help_text="Display label (e.g., 'Color', 'Paper Type')", max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('select', 'Select Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('range', 'Range Slider')], default='select', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('help_text', models.CharField(blank=True, max_length=300)),
                ('options', models.TextField(blank=True, help_text='JSON format: [{"value": "option1", "label": "Option 1", "price_modifier": 0}]')),
                ('default_value', models.CharField(blank=True, max_length=200)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('show_condition', models.CharField(blank=True, help_text='JSON condition for when to show this field', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='services.product')),
            ],
            options={
                'ordering': ['order', 'field_name'],
                'unique_together': {('product', 'field_name')},
            },
        ),
    ]
