# Generated by Django 5.2.6 on 2025-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_category_form_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('book-printing', 'Book Printing'), ('paper-boxes', 'Paper Boxes'), ('marketing-material', 'Marketing Material'), ('stationery', 'Stationery')], max_length=50)),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_type', models.CharField(choices=[('base_price', 'Base Price'), ('quantity_tier', 'Quantity Tier'), ('option_modifier', 'Option Modifier'), ('conditional_pricing', 'Conditional Pricing'), ('page_based_pricing', 'Page-Based Pricing'), ('dimension_based_pricing', 'Dimension-Based Pricing')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of what this rule does')),
                ('conditions', models.JSONField(default=dict, help_text="Conditions for rule application. Format: {'field': 'interior_color', 'value': 'combine_color'}")),
                ('pricing_formula', models.JSONField(default=dict, help_text="Pricing calculation formula. Format: {'base_rate': 2.5, 'multiplier_field': 'page_count'}")),
                ('min_quantity', models.IntegerField(blank=True, help_text='Minimum quantity for this rule', null=True)),
                ('max_quantity', models.IntegerField(blank=True, help_text='Maximum quantity for this rule', null=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage for quantity tiers', max_digits=5)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed price amount for this rule', max_digits=10, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit (e.g., per page, per square inch)', max_digits=10, null=True)),
                ('priority', models.IntegerField(default=0, help_text='Rule priority (higher numbers = higher priority)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category Pricing Rule',
                'verbose_name_plural': 'Category Pricing Rules',
                'ordering': ['category', '-priority', 'rule_name'],
            },
        ),
    ]
