# Generated by Django 5.2.6 on 2025-10-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_category_pricing_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='form_configuration',
            field=models.JSONField(blank=True, default=dict, help_text='Category-specific form configuration and settings'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='has_sequential_form',
            field=models.BooleanField(default=False, help_text='Enable sequential form progression for this category'),
        ),
    ]
