# Generated by Django 5.2.6 on 2025-09-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_productformfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPrintingQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(25, '25 Books'), (50, '50 Books'), (100, '100 Books'), (250, '250 Books'), (500, '500 Books'), (1000, '1000 Books'), (2500, '2500 Books'), (5000, '5000 Books')], default=100)),
                ('book_size', models.CharField(choices=[('A5', 'A5 (148 x 210 mm)'), ('A4', 'A4 (210 x 297 mm)'), ('6x9', '6" x 9" (152 x 229 mm)'), ('8.5x11', '8.5" x 11" (216 x 279 mm)'), ('custom', 'Custom Size')], default='A5', max_length=20)),
                ('page_count', models.IntegerField(choices=[(24, '24 Pages'), (32, '32 Pages'), (48, '48 Pages'), (64, '64 Pages'), (80, '80 Pages'), (100, '100 Pages'), (128, '128 Pages'), (150, '150 Pages'), (200, '200 Pages'), (250, '250 Pages'), (300, '300 Pages')], default=100)),
                ('inner_paper', models.CharField(choices=[('70gsm_offset', '70 GSM Offset Paper'), ('80gsm_offset', '80 GSM Offset Paper'), ('90gsm_offset', '90 GSM Offset Paper'), ('100gsm_art', '100 GSM Art Paper'), ('130gsm_art', '130 GSM Art Paper')], default='70gsm_offset', max_length=20)),
                ('inner_printing', models.CharField(choices=[('bw', 'Black & White'), ('color', 'Full Color (4+4)'), ('mixed', 'Mixed (Some B&W, Some Color)')], default='bw', max_length=10)),
                ('cover_paper', models.CharField(choices=[('250gsm_art', '250 GSM Art Card'), ('300gsm_art', '300 GSM Art Card'), ('350gsm_art', '350 GSM Art Card'), ('250gsm_duplex', '250 GSM Duplex Board'), ('300gsm_duplex', '300 GSM Duplex Board')], default='250gsm_art', max_length=20)),
                ('cover_printing', models.CharField(choices=[('color_4_0', 'Full Color Front Only (4+0)'), ('color_4_4', 'Full Color Both Sides (4+4)'), ('color_4_1', 'Color Front + Black Back (4+1)')], default='color_4_0', max_length=10)),
                ('binding_type', models.CharField(choices=[('saddle_stitch', 'Saddle Stitching'), ('perfect_binding', 'Perfect Binding'), ('spiral_binding', 'Spiral Binding'), ('case_binding', 'Case Binding (Hardcover)'), ('thread_sewing', 'Thread Sewing + Perfect Binding')], default='perfect_binding', max_length=20)),
                ('cover_finish', models.CharField(choices=[('matte', 'Matte Finish'), ('gloss', 'Gloss Lamination'), ('matte_lam', 'Matte Lamination'), ('spot_uv', 'Spot UV'), ('foiling', 'Gold/Silver Foiling'), ('embossing', 'Embossing')], default='matte_lam', max_length=15)),
                ('design_service', models.CharField(choices=[('none', 'No Design Service'), ('basic', 'Basic Design Service (+₹2,500)'), ('premium', 'Premium Design Service (+₹5,000)'), ('formatting', 'Text Formatting Only (+₹1,500)')], default='none', max_length=10)),
                ('isbn_service', models.BooleanField(default=False, verbose_name='ISBN Allocation (+₹500)')),
                ('barcode_service', models.BooleanField(default=False, verbose_name='Barcode Generation (+₹200)')),
                ('copyright_service', models.BooleanField(default=False, verbose_name='Copyright Registration (+₹2,000)')),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrochureQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(100, '100 Pieces'), (250, '250 Pieces'), (500, '500 Pieces'), (1000, '1000 Pieces'), (2500, '2500 Pieces'), (5000, '5000 Pieces')], default=500)),
                ('size', models.CharField(choices=[('A4', 'A4 (210 x 297 mm)'), ('A5', 'A5 (148 x 210 mm)'), ('A3', 'A3 (297 x 420 mm)'), ('dl', 'DL (99 x 210 mm)'), ('custom', 'Custom Size')], default='A4', max_length=10)),
                ('paper_type', models.CharField(choices=[('130gsm_art', '130 GSM Art Paper'), ('170gsm_art', '170 GSM Art Paper'), ('200gsm_art', '200 GSM Art Paper'), ('250gsm_art', '250 GSM Art Card'), ('300gsm_art', '300 GSM Art Card')], default='170gsm_art', max_length=15)),
                ('folding', models.CharField(choices=[('no_fold', 'No Folding (Flat)'), ('half_fold', 'Half Fold'), ('tri_fold', 'Tri-Fold'), ('z_fold', 'Z-Fold'), ('gate_fold', 'Gate Fold')], default='tri_fold', max_length=15)),
                ('printing_sides', models.CharField(choices=[('single', 'Single Side (4+0)'), ('double', 'Double Side (4+4)')], default='double', max_length=10)),
                ('finishing', models.CharField(choices=[('matte', 'Matte Finish'), ('gloss_lam', 'Gloss Lamination'), ('matte_lam', 'Matte Lamination'), ('spot_uv', 'Spot UV')], default='matte_lam', max_length=15)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessCardQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(100, '100 Cards'), (250, '250 Cards'), (500, '500 Cards'), (1000, '1000 Cards'), (2500, '2500 Cards'), (5000, '5000 Cards')], default=500)),
                ('card_size', models.CharField(choices=[('standard', 'Standard (90 x 54 mm)'), ('mini', 'Mini (85 x 50 mm)'), ('square', 'Square (70 x 70 mm)'), ('folded', 'Folded (180 x 54 mm)')], default='standard', max_length=15)),
                ('paper_type', models.CharField(choices=[('300gsm_art', '300 GSM Art Card'), ('350gsm_art', '350 GSM Art Card'), ('400gsm_art', '400 GSM Art Card'), ('300gsm_duplex', '300 GSM Duplex Board'), ('textured', 'Textured Paper'), ('linen', 'Linen Finish')], default='300gsm_art', max_length=20)),
                ('printing_sides', models.CharField(choices=[('single', 'Single Side (4+0)'), ('double', 'Double Side (4+4)')], default='double', max_length=10)),
                ('finishing', models.CharField(choices=[('matte', 'Matte Finish'), ('gloss_lam', 'Gloss Lamination'), ('matte_lam', 'Matte Lamination'), ('spot_uv', 'Spot UV'), ('foiling', 'Gold/Silver Foiling'), ('embossing', 'Embossing')], default='matte_lam', max_length=15)),
                ('design_service', models.CharField(choices=[('none', 'No Design Service'), ('basic', 'Basic Design (+₹500)'), ('premium', 'Premium Design (+₹1,500)')], default='none', max_length=10)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
