# Generated by Django 5.2.6 on 2025-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_bookprintingquote_brochurequote_businesscardquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenBookQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(choices=[(25, '25 Books'), (50, '50 Books'), (100, '100 Books'), (250, '250 Books'), (500, '500 Books'), (1000, '1000 Books')], default=100)),
                ('book_size', models.CharField(choices=[('A5', 'A5 (148 x 210 mm) - Perfect for little hands'), ('A4', 'A4 (210 x 297 mm) - Large format'), ('square', 'Square (200 x 200 mm) - Fun square format'), ('custom', 'Custom Size')], default='A5', max_length=20)),
                ('page_count', models.IntegerField(choices=[(16, '16 Pages - Short story'), (24, '24 Pages - Standard'), (32, '32 Pages - Extended story'), (48, '48 Pages - Chapter book')], default=24)),
                ('age_group', models.CharField(choices=[('toddler', '0-3 Years - Toddlers'), ('preschool', '3-6 Years - Preschool'), ('early_reader', '6-9 Years - Early Readers'), ('middle_grade', '9-12 Years - Middle Grade')], default='preschool', max_length=20)),
                ('inner_paper', models.CharField(choices=[('80gsm_offset', '80 GSM Offset - Standard quality'), ('100gsm_art', '100 GSM Art Paper - Premium quality'), ('130gsm_art', '130 GSM Art Paper - Luxury quality')], default='80gsm_offset', max_length=20)),
                ('inner_printing', models.CharField(choices=[('full_color', 'Full Color - Vibrant illustrations'), ('mixed', 'Mixed - Some color, some B&W'), ('bw', 'Black & White - Text-based')], default='full_color', max_length=15)),
                ('cover_paper', models.CharField(choices=[('300gsm_art', '300 GSM Art Card - Durable'), ('350gsm_art', '350 GSM Art Card - Premium'), ('board_book', 'Board Book - Extra thick for toddlers')], default='300gsm_art', max_length=20)),
                ('binding_type', models.CharField(choices=[('saddle_stitch', 'Saddle Stitching - Standard'), ('perfect_binding', 'Perfect Binding - Professional'), ('spiral_binding', 'Spiral Binding - Easy to flip'), ('board_book_binding', 'Board Book Binding - Toddler-safe')], default='saddle_stitch', max_length=25)),
                ('cover_finish', models.CharField(choices=[('matte_lam', 'Matte Lamination - Smooth finish'), ('gloss_lam', 'Gloss Lamination - Shiny finish'), ('spot_uv', 'Spot UV - Special effects'), ('soft_touch', 'Soft Touch - Velvety feel')], default='matte_lam', max_length=15)),
                ('rounded_corners', models.BooleanField(default=False, verbose_name='Rounded Corners (+₹200)')),
                ('scratch_sniff', models.BooleanField(default=False, verbose_name='Scratch & Sniff Pages (+₹500)')),
                ('pop_up_elements', models.BooleanField(default=False, verbose_name='Pop-up Elements (+₹800)')),
                ('texture_pages', models.BooleanField(default=False, verbose_name='Textured Pages (+₹300)')),
                ('glow_in_dark', models.BooleanField(default=False, verbose_name='Glow-in-Dark Ink (+₹600)')),
                ('sound_module', models.BooleanField(default=False, verbose_name='Sound Module (+₹1200)')),
                ('design_service', models.CharField(choices=[('none', 'I have my own illustrations'), ('basic', 'Basic Illustration Service (+₹5,000)'), ('premium', 'Premium Illustration Service (+₹10,000)'), ('custom', 'Custom Character Design (+₹15,000)')], default='none', max_length=15)),
                ('writing_service', models.CharField(choices=[('none', 'I have my own story'), ('editing', 'Story Editing & Proofreading (+₹2,000)'), ('ghostwriting', 'Professional Story Writing (+₹8,000)')], default='none', max_length=15)),
                ('publishing_service', models.CharField(choices=[('none', 'Print only'), ('isbn', 'ISBN Allocation (+₹500)'), ('full_publishing', 'Full Publishing Package (+₹3,000)')], default='none', max_length=15)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
                ('book_title', models.CharField(blank=True, max_length=200, verbose_name='Book Title (Optional)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
