# Generated by Django 5.2.8 on 2025-12-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_update_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticproduct',
            name='group_name',
            field=models.CharField(blank=True, help_text="Group name for mega menu (e.g., 'Business Card', 'Letter Head')", max_length=100),
        ),
        migrations.AddField(
            model_name='staticproduct',
            name='group_order',
            field=models.IntegerField(default=0, help_text='Order of the group in the menu'),
        ),
    ]
