# Generated by Django 5.2.8 on 2026-01-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_sample_service_info_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('select', 'Select Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('range', 'Range Slider'), ('file', 'File Upload'), ('conditional_group', 'Conditional Field Group'), ('image_grid', 'Image Grid Selector')], default='select', max_length=20),
        ),
    ]
