# Generated by Django 5.2.15 on 2026-07-02 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0014_add_both_option_to_printing_side"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductFieldOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Text the customer sees, e.g. 'Front & Back' or 'Rounded Corners'",
                        max_length=200,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        blank=True,
                        help_text="Internal value saved with the order. Leave blank to auto-fill from the label.",
                        max_length=200,
                    ),
                ),
                (
                    "price_modifier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Extra charge in ₹ added when this option is chosen. 0 = no change, negative = discount.",
                        max_digits=10,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        help_text="Optional image path (used only by image-grid fields).",
                        max_length=500,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                (
                    "width_mm",
                    models.CharField(
                        blank=True,
                        help_text="Optional — canvas width in mm for the design tool.",
                        max_length=20,
                    ),
                ),
                (
                    "height_mm",
                    models.CharField(
                        blank=True,
                        help_text="Optional — canvas height in mm for the design tool.",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_options",
                        to="services.productformfield",
                    ),
                ),
            ],
            options={
                "ordering": ["field", "order", "id"],
            },
        ),
    ]
