# Generated by Django 5.2.15 on 2026-07-02 06:12

import json
from decimal import Decimal, InvalidOperation

from django.db import migrations


def _to_decimal(value):
    try:
        return Decimal(str(value or 0))
    except (InvalidOperation, TypeError, ValueError):
        return Decimal("0")


def populate_options(apps, schema_editor):
    """Move each field's JSON options into normalized ProductFieldOption rows."""
    ProductFormField = apps.get_model("services", "ProductFormField")
    ProductFieldOption = apps.get_model("services", "ProductFieldOption")

    for field in ProductFormField.objects.all():
        if not field.options:
            continue
        # Skip if rows already exist (idempotent / safe re-run)
        if ProductFieldOption.objects.filter(field=field).exists():
            continue
        try:
            options = json.loads(field.options)
        except (json.JSONDecodeError, TypeError):
            continue
        if not isinstance(options, list):
            continue

        for i, opt in enumerate(options):
            if not isinstance(opt, dict):
                continue
            label = opt.get("label") or opt.get("value") or f"Option {i + 1}"
            value = opt.get("value") or label
            ProductFieldOption.objects.create(
                field=field,
                label=label,
                value=value,
                price_modifier=_to_decimal(opt.get("price_modifier", 0)),
                image_url=opt.get("image_url", "") or "",
                description=opt.get("description", "") or "",
                width_mm=str(opt.get("width_mm", "") or ""),
                height_mm=str(opt.get("height_mm", "") or ""),
                order=i,
                is_active=True,
            )


def reverse_populate(apps, schema_editor):
    """Delete all normalized rows (JSON blobs are untouched, so this is safe)."""
    ProductFieldOption = apps.get_model("services", "ProductFieldOption")
    ProductFieldOption.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0015_productfieldoption"),
    ]

    operations = [
        migrations.RunPython(populate_options, reverse_populate),
    ]
