# Generated by Django 5.2.15 on 2026-07-02 06:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0016_populate_field_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookPrintingPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color_bw_standard_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.50"),
                        max_digits=8,
                        verbose_name="B&W Standard (per page)",
                    ),
                ),
                (
                    "color_bw_premium_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=8,
                        verbose_name="B&W Premium (per page)",
                    ),
                ),
                (
                    "color_standard_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6.00"),
                        max_digits=8,
                        verbose_name="Colour Standard (per page)",
                    ),
                ),
                (
                    "color_premium_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8.00"),
                        max_digits=8,
                        verbose_name="Colour Premium (per page)",
                    ),
                ),
                (
                    "combine_bw_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=8,
                        verbose_name="Combined: B&W pages (per page)",
                    ),
                ),
                (
                    "combine_color_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("6.00"),
                        max_digits=8,
                        verbose_name="Combined: Colour pages (per page)",
                    ),
                ),
                (
                    "size_a4",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="A4",
                    ),
                ),
                (
                    "size_letter",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25"),
                        max_digits=8,
                        verbose_name="Letter",
                    ),
                ),
                (
                    "size_executive",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=8,
                        verbose_name="Executive",
                    ),
                ),
                (
                    "size_a5",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("-25"),
                        max_digits=8,
                        verbose_name="A5",
                    ),
                ),
                (
                    "paper_75gsm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="75 GSM",
                    ),
                ),
                (
                    "paper_100gsm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=8,
                        verbose_name="100 GSM",
                    ),
                ),
                (
                    "paper_100gsm_art",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        max_digits=8,
                        verbose_name="100 GSM Art",
                    ),
                ),
                (
                    "paper_130gsm_art",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("150"),
                        max_digits=8,
                        verbose_name="130 GSM Art",
                    ),
                ),
                (
                    "binding_saddle_stitch",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Saddle Stitch",
                    ),
                ),
                (
                    "binding_spiral",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        max_digits=8,
                        verbose_name="Spiral Binding",
                    ),
                ),
                (
                    "binding_paperback_perfect",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("200"),
                        max_digits=8,
                        verbose_name="Paperback / Perfect",
                    ),
                ),
                (
                    "binding_hardcover",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500"),
                        max_digits=8,
                        verbose_name="Hardcover",
                    ),
                ),
                (
                    "cover_matte",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=8,
                        verbose_name="Matte",
                    ),
                ),
                (
                    "cover_glossy",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=8,
                        verbose_name="Glossy",
                    ),
                ),
                (
                    "cover_design_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1500"),
                        max_digits=8,
                        verbose_name="Cover page design (flat)",
                    ),
                ),
                (
                    "inner_page_design_per_page",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=8,
                        verbose_name="Inner page design (per page)",
                    ),
                ),
                (
                    "isbn_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2000"),
                        max_digits=8,
                        verbose_name="ISBN allocation (flat)",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Book Printing Pricing",
                "verbose_name_plural": "Book Printing Pricing",
            },
        ),
    ]
