# Generated by Django 5.2.15 on 2026-07-02 09:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0017_bookprintingpricing"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookprintingpricing",
            name="bulk_disc_1",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5"),
                max_digits=5,
                verbose_name="Bulk tier 1 — discount %",
            ),
        ),
        migrations.AddField(
            model_name="bookprintingpricing",
            name="bulk_disc_2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                max_digits=5,
                verbose_name="Bulk tier 2 — discount %",
            ),
        ),
        migrations.AddField(
            model_name="bookprintingpricing",
            name="bulk_qty_1",
            field=models.PositiveIntegerField(
                default=50, verbose_name="Bulk tier 1 — minimum qty"
            ),
        ),
        migrations.AddField(
            model_name="bookprintingpricing",
            name="bulk_qty_2",
            field=models.PositiveIntegerField(
                default=100, verbose_name="Bulk tier 2 — minimum qty"
            ),
        ),
        migrations.CreateModel(
            name="QuantityTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        help_text="Discount applies when order quantity is at least this"
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percent off the subtotal, e.g. 10 = 10% off",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qty_tiers",
                        to="services.staticproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "min_quantity"],
                "unique_together": {("product", "min_quantity")},
            },
        ),
    ]
