# Generated by Django 5.2.15 on 2026-07-11 06:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0018_bookprintingpricing_bulk_disc_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookprintingpricing",
            name="bulk_disc_3",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("15"),
                max_digits=5,
                verbose_name="Bulk tier 3 — discount %",
            ),
        ),
        migrations.AddField(
            model_name="bookprintingpricing",
            name="bulk_qty_3",
            field=models.PositiveIntegerField(
                default=200, verbose_name="Bulk tier 3 — minimum qty"
            ),
        ),
    ]
