# Generated by Django 5.2.15 on 2026-07-11 06:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0019_bookprintingpricing_bulk_disc_3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookprintingpricing",
            name="bulk_disc_1",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                max_digits=5,
                verbose_name="Bulk tier 1 — discount %",
            ),
        ),
        migrations.AlterField(
            model_name="bookprintingpricing",
            name="bulk_disc_2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12"),
                max_digits=5,
                verbose_name="Bulk tier 2 — discount %",
            ),
        ),
        migrations.AlterField(
            model_name="bookprintingpricing",
            name="bulk_disc_3",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("14"),
                max_digits=5,
                verbose_name="Bulk tier 3 — discount %",
            ),
        ),
        migrations.AlterField(
            model_name="bookprintingpricing",
            name="bulk_qty_1",
            field=models.PositiveIntegerField(
                default=200, verbose_name="Bulk tier 1 — minimum qty"
            ),
        ),
        migrations.AlterField(
            model_name="bookprintingpricing",
            name="bulk_qty_2",
            field=models.PositiveIntegerField(
                default=250, verbose_name="Bulk tier 2 — minimum qty"
            ),
        ),
        migrations.AlterField(
            model_name="bookprintingpricing",
            name="bulk_qty_3",
            field=models.PositiveIntegerField(
                default=300, verbose_name="Bulk tier 3 — minimum qty"
            ),
        ),
    ]
