# Generated by Django 5.2.15 on 2026-07-15 06:26

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0020_alter_bookprintingpricing_bulk_disc_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookprintingpricing",
            name="page_price_matrix",
            field=models.JSONField(
                default=apps.services.models.default_page_price_matrix,
                verbose_name="Per-page price matrix",
            ),
        ),
    ]
