# Generated by Django 5.2.15 on 2026-07-21 12:17

import apps.services.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0021_bookprintingpricing_page_price_matrix"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookprintingpricing",
            name="page_price_components",
            field=models.JSONField(
                default=apps.services.models.default_page_price_components,
                help_text="Printing and paper costs that make up each per-page matrix rate.",
                verbose_name="Workbook price components",
            ),
        ),
    ]
