# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('animated', 'Animated'), ('luxury', 'Luxury')], default='basic', max_length=10)),
                ('coin_cost', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('diamond_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('icon_url', models.URLField(blank=True)),
                ('animation_url', models.URLField(blank=True)),
                ('animation_type', models.CharField(default='svga', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'Top-up (IAP)'), ('gift', 'Gift'), ('payout', 'Payout (diamond->cash)'), ('reward', 'Reward grant'), ('refund', 'Refund'), ('convert', 'Diamond->coin convert'), ('purchase', 'In-app item purchase')], db_index=True, max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='completed', max_length=10)),
                ('idempotency_key', models.CharField(db_index=True, max_length=80, unique=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_txns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('recipient_count', models.PositiveIntegerField(default=1)),
                ('combo', models.PositiveIntegerField(default=1)),
                ('total_coin_cost', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='economy.gift')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_events', to='economy.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_balance', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('diamond_balance', models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('lifetime_coins_spent', models.BigIntegerField(default=0)),
                ('lifetime_diamonds_earned', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_system', models.BooleanField(default=False)),
                ('currency', models.CharField(choices=[('coin', 'Coin'), ('diamond', 'Diamond')], max_length=8)),
                ('amount', models.BigIntegerField()),
                ('balance_after', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='economy.transaction')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='economy.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='GiftRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diamonds_awarded', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='economy.giftevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status', '-created_at'], name='economy_tra_type_0eb6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='giftevent',
            index=models.Index(fields=['room_id', '-created_at'], name='economy_gif_room_id_25bc78_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['wallet', 'currency', '-created_at'], name='economy_led_wallet__04112d_idx'),
        ),
    ]
