# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('coin_cost', models.PositiveIntegerField()),
                ('icon_url', models.URLField(blank=True)),
                ('tier', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('ended', 'Ended')], db_index=True, default='active', max_length=10)),
                ('growth_points', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('graduated_at', models.DateTimeField(blank=True, null=True)),
                ('disciple', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor', to=settings.AUTH_USER_MODEL)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('engaged', 'Engaged (proposed)'), ('married', 'Married'), ('divorced', 'Divorced')], db_index=True, default='engaged', max_length=10)),
                ('affection', models.BigIntegerField(default=0)),
                ('blessing', models.BigIntegerField(default=0)),
                ('room_id', models.CharField(blank=True, max_length=32)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('married_at', models.DateTimeField(blank=True, null=True)),
                ('divorced_at', models.DateTimeField(blank=True, null=True)),
                ('partner_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_a', to=settings.AUTH_USER_MODEL)),
                ('partner_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_b', to=settings.AUTH_USER_MODEL)),
                ('ring', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='relationships.ring')),
            ],
            options={
                'indexes': [models.Index(fields=['partner_a', 'status'], name='relationshi_partner_2d88c5_idx'), models.Index(fields=['partner_b', 'status'], name='relationshi_partner_6efad9_idx')],
            },
        ),
    ]
