# Generated by Django 5.2.6 on 2025-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsubmission_faqcategory_page_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepageslider',
            name='background_gradient_from',
            field=models.CharField(default='from-blue-50', help_text='Tailwind gradient from class', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='background_gradient_to',
            field=models.CharField(default='to-purple-50', help_text='Tailwind gradient to class', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='background_gradient_via',
            field=models.CharField(default='via-indigo-50', help_text='Tailwind gradient via class', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='primary_cta_text',
            field=models.CharField(blank=True, help_text='Primary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='primary_cta_url',
            field=models.CharField(blank=True, help_text='Primary button link', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='secondary_cta_text',
            field=models.CharField(blank=True, help_text='Secondary button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='secondary_cta_url',
            field=models.CharField(blank=True, help_text='Secondary button link', max_length=200),
        ),
        migrations.AddField(
            model_name='homepageslider',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle/tagline', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='cta_text',
            field=models.CharField(blank=True, help_text='Legacy button text', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepageslider',
            name='cta_url',
            field=models.CharField(blank=True, help_text='Legacy button link', max_length=200),
        ),
    ]
