# Generated by Django 5.2.15 on 2026-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_site_settings_services_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("twitter", "X (Twitter)"),
                    ("linkedin", "LinkedIn"),
                    ("youtube", "YouTube"),
                    ("pinterest", "Pinterest"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("tiktok", "TikTok"),
                    ("custom", "Custom (paste SVG below)"),
                ],
                default="facebook",
                help_text="Pick a platform — the icon is set automatically.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="icon_svg",
            field=models.TextField(
                blank=True,
                help_text="Only needed when platform is 'Custom' — paste raw SVG markup here.",
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="Optional. Leave blank to use the platform name.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="url",
            field=models.CharField(
                default="#",
                help_text="Full link, e.g. https://facebook.com/yourpage",
                max_length=200,
            ),
        ),
    ]
