# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.db.models.deletion
import rooms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PKBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_a_id', models.CharField(blank=True, max_length=32)),
                ('room_b_id', models.CharField(blank=True, max_length=32)),
                ('score_a', models.BigIntegerField(default=0)),
                ('score_b', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=10)),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ends_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('side_a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_as_a', to=settings.AUTH_USER_MODEL)),
                ('side_b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pk_as_b', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pk_wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, default=rooms.models._gen_room_id, max_length=32, unique=True)),
                ('title', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('public', 'Public'), ('private', 'Private (password)'), ('event', 'Event')], default='public', max_length=10)),
                ('category', models.CharField(choices=[('chat', 'Chat'), ('music', 'Music'), ('games', 'Games'), ('dating', 'Dating')], default='chat', max_length=10)),
                ('status', models.CharField(choices=[('live', 'Live'), ('closed', 'Closed')], db_index=True, default='live', max_length=8)),
                ('password_hash', models.CharField(blank=True, max_length=128)),
                ('theme', models.CharField(blank=True, max_length=40)),
                ('cover_url', models.URLField(blank=True)),
                ('seat_count', models.PositiveSmallIntegerField(default=8)),
                ('occupant_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_rooms', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField()),
                ('muted', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occupant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupied_seats', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='rooms.room')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'category'], name='rooms_room_status_698db5_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', '-occupant_count'], name='rooms_room_status_190800_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='roomban',
            unique_together={('room', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='seatstate',
            unique_together={('room', 'index')},
        ),
    ]
