# Generated by Django 6.0.6 on 2026-06-18 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('coin_cost', models.PositiveIntegerField(default=0)),
                ('preview_url', models.URLField(blank=True)),
                ('assets', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('wedding', 'Wedding'), ('auction', 'Auction'), ('party', 'Party / Music'), ('gaming', 'Gaming'), ('dating', 'Dating')], db_index=True, default='standard', max_length=12),
        ),
        migrations.CreateModel(
            name='RoomThemeOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='rooms.roomtheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_themes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'theme')},
            },
        ),
    ]
