# Generated by Django 6.0.7 on 2026-07-11 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_roomtheme_room_room_type_roomthemeownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('emoji', models.CharField(default='👑', max_length=8)),
                ('image_url', models.URLField(blank=True)),
                ('starting_bid', models.PositiveIntegerField(default=1000)),
                ('min_increment', models.PositiveIntegerField(default=1000)),
                ('current_bid', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('sold', 'Sold'), ('unsold', 'Unsold (no bids)'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=12)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_lots', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_lots', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpinRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('betting', 'Betting open'), ('spinning', 'Spinning'), ('settled', 'Settled')], db_index=True, default='betting', max_length=10)),
                ('server_seed', models.CharField(max_length=64)),
                ('server_seed_hash', models.CharField(max_length=64)),
                ('winning_symbol', models.CharField(blank=True, max_length=8)),
                ('bets_close_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_rounds', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('refunded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_bids', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rooms.auctionlot')),
            ],
            options={
                'ordering': ['-amount', 'created_at'],
                'indexes': [models.Index(fields=['lot', '-amount'], name='rooms_aucti_lot_id_9bc828_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpinBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=8)),
                ('amount', models.PositiveIntegerField()),
                ('payout', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spin_bets', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='rooms.spinround')),
            ],
            options={
                'indexes': [models.Index(fields=['round', 'symbol'], name='rooms_spinb_round_i_cc65b5_idx')],
            },
        ),
    ]
