# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('slot', models.CharField(choices=[('frame', 'Avatar frame'), ('bubble', 'Chat bubble'), ('entrance', 'Entrance effect'), ('name_color', 'Name color'), ('badge', 'Badge'), ('avatar_part', '3D avatar part')], db_index=True, max_length=15)),
                ('asset_url', models.URLField(blank=True)),
                ('coin_cost', models.PositiveIntegerField(default=0)),
                ('is_purchasable', models.BooleanField(default=False)),
                ('vip_only_level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', 'Purchase'), ('loot', 'Loot box'), ('event', 'Event reward'), ('vip', 'VIP perk'), ('gift', 'Gift')], max_length=10)),
                ('equipped', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_by', to='inventory.cosmeticitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'equipped'], name='inventory_i_user_id_b68102_idx')],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
