# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='FraudFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('velocity_topup', 'Top-up velocity'), ('velocity_gift', 'Gift velocity'), ('velocity_payout', 'Payout velocity'), ('collusion', 'Collusion ring'), ('laundering', 'Suspected laundering'), ('chargeback', 'Chargeback after spend'), ('device_sharing', 'Shared device fingerprint')], db_index=True, max_length=20)),
                ('severity', models.FloatField(default=0.5)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'resolved', '-created_at'], name='fraud_fraud_user_id_6266a5_idx')],
            },
        ),
    ]
