# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('mode', models.CharField(choices=[('turn', 'Turn-based'), ('realtime', 'Real-time'), ('round', 'Round-based')], default='turn', max_length=10)),
                ('bundle_url', models.URLField()),
                ('min_players', models.PositiveSmallIntegerField(default=2)),
                ('max_players', models.PositiveSmallIntegerField(default=4)),
                ('supports_bots', models.BooleanField(default=False)),
                ('is_staked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('lobby', 'Lobby (waiting)'), ('playing', 'Playing'), ('finished', 'Finished'), ('abandoned', 'Abandoned')], db_index=True, default='lobby', max_length=10)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('rng_seed', models.BigIntegerField(default=0)),
                ('stake_coins', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='games.gamedefinition')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_games', to=settings.AUTH_USER_MODEL)),
                ('pot_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='economy.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_slot', models.PositiveSmallIntegerField()),
                ('is_bot', models.BooleanField(default=False)),
                ('team', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('none', 'None'), ('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], default='none', max_length=5)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_plays', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.gamesession')),
            ],
            options={
                'ordering': ['seat_slot'],
            },
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['room_id', 'status'], name='games_games_room_id_6705c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('session', 'seat_slot')},
        ),
    ]
