# Generated by Django 4.2.7 on 2025-09-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Template Categories",
            },
        ),
        migrations.CreateModel(
            name="UserDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("canvas_data", models.JSONField(help_text="Fabric.js canvas JSON")),
                (
                    "preview_image",
                    models.ImageField(blank=True, upload_to="designs/previews/"),
                ),
                ("width_mm", models.FloatField()),
                ("height_mm", models.FloatField()),
                ("bleed_mm", models.FloatField(default=3.0)),
                ("safe_zone_mm", models.FloatField(default=5.0)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("thumbnail", models.ImageField(upload_to="templates/thumbnails/")),
                (
                    "preview_image",
                    models.ImageField(blank=True, upload_to="templates/previews/"),
                ),
                (
                    "svg_file",
                    models.FileField(
                        blank=True,
                        help_text="SVG template file",
                        upload_to="templates/svg/",
                    ),
                ),
                (
                    "json_data",
                    models.JSONField(
                        blank=True, help_text="Fabric.js JSON data", null=True
                    ),
                ),
                ("width_mm", models.FloatField()),
                ("height_mm", models.FloatField()),
                ("bleed_mm", models.FloatField(default=3.0)),
                ("safe_zone_mm", models.FloatField(default=5.0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="templates_mgmt.templatecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
