# Generated by Django 4.2.7 on 2025-09-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_pricingtier_shippingoption_alter_product_options_and_more"),
        ("templates_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdesign",
            name="product",
        ),
        migrations.AddField(
            model_name="userdesign",
            name="static_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.staticproduct",
            ),
        ),
        migrations.CreateModel(
            name="StaticProductTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "template_data",
                    models.JSONField(help_text="Fabric.js template JSON"),
                ),
                (
                    "thumbnail",
                    models.ImageField(upload_to="static_product_templates/thumbnails/"),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True, upload_to="static_product_templates/previews/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Template category (e.g., Corporate, Creative)",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "static_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_templates",
                        to="services.staticproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
