# Generated by Django 6.0.6 on 2026-06-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "templates_mgmt",
            "0002_remove_userdesign_product_userdesign_static_product_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="designtemplate",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("", "Both / Generic"), ("front", "Front"), ("back", "Back")],
                default="",
                help_text="Which side this template is for. Leave blank for generic/both.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="staticproducttemplate",
            name="side",
            field=models.CharField(
                blank=True,
                choices=[("", "Both / Generic"), ("front", "Front"), ("back", "Back")],
                default="",
                help_text="Which side this template is for. Leave blank for generic/both.",
                max_length=10,
            ),
        ),
    ]
