# Generated by Django 4.2.7 on 2025-09-25 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("templates_mgmt", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClipartLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("svg_content", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="clipart/thumbnails/")),
                ("category", models.CharField(max_length=100)),
                (
                    "tags",
                    models.CharField(help_text="Comma-separated tags", max_length=500),
                ),
                ("primary_color", models.CharField(default="#000000", max_length=7)),
                ("has_multiple_colors", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="FontLibrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                ("font_family", models.CharField(max_length=200)),
                ("font_file", models.FileField(upload_to="fonts/")),
                ("font_weight", models.CharField(default="400", max_length=20)),
                ("font_style", models.CharField(default="normal", max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("serif", "Serif"),
                            ("sans-serif", "Sans Serif"),
                            ("monospace", "Monospace"),
                            ("cursive", "Cursive"),
                            ("fantasy", "Fantasy"),
                            ("display", "Display"),
                        ],
                        default="sans-serif",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("file_size", models.PositiveIntegerField()),
                (
                    "preview_text",
                    models.CharField(
                        default="The quick brown fox jumps over the lazy dog",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "display_name"],
            },
        ),
        migrations.CreateModel(
            name="DesignSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("actions_count", models.IntegerField(default=0)),
                ("design_saved", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField()),
                ("position_x", models.FloatField(blank=True, null=True)),
                ("position_y", models.FloatField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="templates_mgmt.userdesign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("font", "Font"),
                            ("svg", "SVG"),
                            ("template", "Template"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="design_assets/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, upload_to="design_assets/thumbnails/"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("add_text", "Add Text"),
                            ("add_image", "Add Image"),
                            ("add_shape", "Add Shape"),
                            ("add_clipart", "Add Clipart"),
                            ("modify_object", "Modify Object"),
                            ("delete_object", "Delete Object"),
                            ("move_object", "Move Object"),
                            ("resize_object", "Resize Object"),
                            ("rotate_object", "Rotate Object"),
                            ("change_color", "Change Color"),
                            ("change_font", "Change Font"),
                            ("apply_template", "Apply Template"),
                            ("save_design", "Save Design"),
                            ("export_design", "Export Design"),
                        ],
                        max_length=50,
                    ),
                ),
                ("canvas_state_before", models.JSONField(blank=True, null=True)),
                ("canvas_state_after", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="design_tool.designsession",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DesignVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("canvas_data", models.JSONField()),
                (
                    "preview_image",
                    models.ImageField(blank=True, upload_to="design_versions/"),
                ),
                ("changes_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="templates_mgmt.userdesign",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("design", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="DesignCollaboration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("comment", "View & Comment"),
                            ("edit", "Full Edit Access"),
                        ],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("shared_at", models.DateTimeField(auto_now_add=True)),
                ("accessed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "design",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborations",
                        to="templates_mgmt.userdesign",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_by_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_designs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shared_at"],
                "unique_together": {("design", "shared_with")},
            },
        ),
    ]
