# Generated by Django 4.2.7 on 2025-09-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0005_auto_20250928_0202"),
        ("design_tool", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designsession",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.staticproduct",
            ),
        ),
    ]
