# Generated by Django 6.0.6 on 2026-06-17 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('room', 'Room'), ('post', 'Post'), ('message', 'Message')], db_index=True, max_length=10)),
                ('target_ref', models.CharField(db_index=True, max_length=64)),
                ('reason', models.CharField(choices=[('harassment', 'Harassment / bullying'), ('hate', 'Hate speech'), ('sexual', 'Sexual content'), ('minor_safety', 'Minor safety'), ('scam', 'Scam / fraud'), ('self_harm', 'Self-harm'), ('violence', 'Violence / threats'), ('spam', 'Spam'), ('other', 'Other')], db_index=True, max_length=15)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('triaged', 'Triaged'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=10)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High'), (3, 'Critical')], db_index=True, default=1)),
                ('primary_reason', models.CharField(choices=[('harassment', 'Harassment / bullying'), ('hate', 'Hate speech'), ('sexual', 'Sexual content'), ('minor_safety', 'Minor safety'), ('scam', 'Scam / fraud'), ('self_harm', 'Self-harm'), ('violence', 'Violence / threats'), ('spam', 'Spam'), ('other', 'Other')], max_length=15)),
                ('report_count', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_cases', to=settings.AUTH_USER_MODEL)),
                ('reports', models.ManyToManyField(blank=True, related_name='cases', to='moderation.report')),
            ],
        ),
        migrations.CreateModel(
            name='AutoModEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text'), ('image', 'Image')], max_length=6)),
                ('category', models.CharField(max_length=30)),
                ('score', models.FloatField()),
                ('context_ref', models.CharField(blank=True, max_length=120)),
                ('auto_actioned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automod_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='moderation__user_id_a6df09_idx'), models.Index(fields=['category', '-score'], name='moderation__categor_d4ec76_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warn', 'Warning'), ('mute', 'Mute (timed)'), ('room_ban', 'Room ban'), ('suspend', 'Account suspension (timed)'), ('ban', 'Account ban (permanent)'), ('shadow', 'Shadow restrict'), ('content_remove', 'Content removal')], db_index=True, max_length=15)),
                ('reason', models.CharField(max_length=300)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_issued', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='moderation.moderationcase')),
            ],
            options={
                'indexes': [models.Index(fields=['target_user', 'active', 'kind'], name='moderation__target__e0e3f1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reason', '-created_at'], name='moderation__reason_cc8d91_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_user', '-created_at'], name='moderation__reporte_9007a7_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationcase',
            index=models.Index(fields=['status', '-priority', '-report_count'], name='moderation__status_acb523_idx'),
        ),
    ]
